export enum PersonIds {
    maksimLiksutov = '3',
    romanLatypov = '39',
    elenaKudryashova = '16',
    oksanaVorobyova = '45',
    ibragimGaziev = '21',
    hamidBulatov = '40',
    alexeyKostromin = '54',
    harutyunOganesyan = '52',
    igorKrasnozhen = '53',
    andreyKorneev = '10',
    olegZaitsev = '26',
    pavelMikhailov = '49',
    alexanderGarakoev = '11',
    valeryGrudev = '25',
    khasyanProkurorov = '46',
    denisFalin = '48',
    alexeyMityaev = '41',
    vladimirMakarov = '42',
    sergeyAlexyuk = '50',
    dmitrySokolov = '51',
    dmitryPronin = '9',
    yuliaTemnikova = '43',
    irinaYefimova = '13',
    anastasiaShaliapina = '14',
    andreyBabarykin = '55',
}
