import {
    InternationalSummit1,
    InternationalSummit10,
    InternationalSummit11,
    InternationalSummit12,
    InternationalSummit13,
    InternationalSummit14,
    InternationalSummit15,
    InternationalSummit16,
    InternationalSummit17,
    InternationalSummit18,
    InternationalSummit19,
    InternationalSummit2,
    InternationalSummit3,
    InternationalSummit4,
    InternationalSummit5,
    InternationalSummit6,
    InternationalSummit7,
    InternationalSummit8,
    InternationalSummit9,
} from '@/Images'
import { cn } from '@/utils'

export const images = [
    { img: InternationalSummit1, className: cn('col-span-9', 'md:h-[450px]') },
    { img: InternationalSummit2, className: cn('col-span-3', 'md:h-[200px]') },
    { img: InternationalSummit3, className: cn('col-span-3', 'md:h-[200px]') },
    { img: InternationalSummit4, className: cn('col-span-3', 'md:h-[200px]') },
    { img: InternationalSummit5, className: cn('col-span-5', 'md:h-[200px]') },
    { img: InternationalSummit6, className: cn('col-span-4', 'md:h-[200px]') },
    { img: InternationalSummit7, className: cn('col-span-9', 'md:h-[450px]') },
    { img: InternationalSummit8, className: cn('col-span-3', 'md:h-[200px]') },
    { img: InternationalSummit9, className: cn('col-span-3', 'md:h-[200px]') },
    { img: InternationalSummit10, className: cn('col-span-3', 'md:h-[200px]') },
    { img: InternationalSummit11, className: cn('col-span-5', 'md:h-[200px]') },
    { img: InternationalSummit12, className: cn('col-span-4', 'md:h-[200px]') },
    { img: InternationalSummit13, className: cn('col-span-9', 'md:h-[450px]') },
    { img: InternationalSummit14, className: cn('col-span-3', 'h-[85px] md:h-[200px]') },
    { img: InternationalSummit15, className: cn('col-span-3', 'h-[85px] md:h-[200px]', 'object-top') },
    { img: InternationalSummit16, className: cn('col-span-3', 'h-[85px] md:h-[200px]') },
    { img: InternationalSummit17, className: cn('col-span-5', 'md:h-[200px]') },
    { img: InternationalSummit18, className: cn('col-span-4', 'md:h-[200px]') },
    { img: InternationalSummit19, className: cn('col-span-9', 'md:h-[450px]') },
]
